=== indabamarcins/module-gulp/etc/gulp.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="gulp">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="task" type="taskType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="taskType">
        <xs:sequence>
            <xs:element name="dependencies" type="dependenciesType" minOccurs="0" maxOccurs="1" />
            <xs:element name="subtasks" type="subtasksType" minOccurs="0" maxOccurs="1" />
            <xs:element name="source" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="dependenciesType">
        <xs:sequence>
            <xs:element name="package" type="packageType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="packageType">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="version" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="subtasksType">
        <xs:sequence>
            <xs:element name="task" type="subtaskType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="subtaskType">
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== indabamarcins/module-gulp/etc/gulp.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gulp
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="urn:magento:module:MaxBucknell_Gulp:etc/gulp.xsd"
>
    <task name="default">
        <dependencies>
            <package name="gulp" version="^3.9.1" />
            <package name="gulp-other" version="^3.9.1" />
        </dependencies>

        <subtasks>
            <task name="less" />
        </subtasks>
    </task>

    <task name="less">
        <dependencies>
            <package name="gulp-less" version="^3.3.0" />
        </dependencies>

        <source>script.js</source>
    </task>
</gulp>
